<?php
/**
 * @author MageRocket
 * @copyright Copyright (c) 2025 MageRocket (https://magerocket.com/)
 * @link https://magerocket.com/
 */

namespace MageRocket\GoCuotas\Controller\Adminhtml\Secret;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\Config\Storage\WriterInterface;
use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\Encryption\EncryptorInterface;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Math\Random;
use MageRocket\GoCuotas\Helper\Data;
use Magento\Framework\App\Cache\TypeListInterface as CacheTypeList;
use Magento\Backend\Model\Auth\Session as AuthSession;

class Regenerate extends Action
{
    // Secret XML Path
    protected const GOCUOTAS_SECRET_XML_PATH = 'payment/gocuotas/secret';

    // Secret Prefix. DO NOT CHANGE!
    private const GOCUTAS_SECRET_PREFIX = 'ag';

    /**
     * @var WriterInterface $configWriter
     */
    protected WriterInterface $configWriter;

    /**
     * @var ScopeConfigInterface $scopeConfig
     */
    protected ScopeConfigInterface $scopeConfig;

    /**
     * @var EncryptorInterface $encryptor
     */
    protected EncryptorInterface $encryptor;

    /**
     * @var ResultFactory $resultFactory
     */
    protected $resultFactory;

    /**
     * @var Random $random
     */
    protected Random $random;

    /**
     * @var Data $helper
     */
    protected Data $helper;

    /**
     * @var CacheTypeList $cacheTypeList
     */
    protected cacheTypeList $cacheTypeList;

    /**
     * @var AuthSession $authSession
     */
    protected AuthSession $authSession;

    /**
     * Construct
     *
     * @param Data $helper
     * @param Random $random
     * @param Context $context
     * @param AuthSession $authSession
     * @param CacheTypeList $cacheTypeList
     * @param EncryptorInterface $encryptor
     * @param WriterInterface $configWriter
     * @param ResultFactory $resultFactory
     * @param ScopeConfigInterface $scopeConfig
     */
    public function __construct(
        Data $helper,
        Random $random,
        Context $context,
        AuthSession $authSession,
        CacheTypeList $cacheTypeList,
        EncryptorInterface $encryptor,
        WriterInterface $configWriter,
        ResultFactory $resultFactory,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->helper = $helper;
        $this->random = $random;
        $this->encryptor = $encryptor;
        $this->authSession = $authSession;
        $this->scopeConfig = $scopeConfig;
        $this->cacheTypeList = $cacheTypeList;
        $this->resultFactory = $resultFactory;
        $this->configWriter = $configWriter;
        parent::__construct($context);
    }

    /**
     * Execute
     */
    public function execute()
    {
        try {
            $secret = self::GOCUTAS_SECRET_PREFIX . $this->random->getRandomString(25);
            $this->configWriter->save(
                self::GOCUOTAS_SECRET_XML_PATH,
                $this->encryptor->encrypt($secret)
            );
            $this->cacheTypeList->cleanType('config');
            $this->messageManager->addSuccessMessage(__('Go Cuotas: Secret has been regenerated.'));
            $user = $this->authSession->getUser();
            $username = $user ? ($user->getUserName() ?? $user->getUsername()) : 'Unknown';
            $this->helper->log("Secret regenerated by $username");
        } catch (LocalizedException $e) {
            $this->helper->log("Regenerate Secret error:" . $e->getMessage());
            $this->messageManager->addErrorMessage(__('Go Cuotas: Error regenerating the secret. Please try again.'));
        }

        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        $resultRedirect->setUrl($this->_redirect->getRefererUrl());
        return $resultRedirect;
    }
}
