<?php
/**
 * @author MageRocket
 * @copyright Copyright (c) 2024 MageRocket (https://magerocket.com/)
 * @link https://magerocket.com/
 */

/** @var $block MageRocket\GoCuotas\Block\Onepage\Failure */
/** @var $escaper Magento\Framework\Escaper */
$order = $block->getOrder();
?>
<?php if ($block->isPaymentMethodGoCuotas()): ?>
    <div class="gocuotas-payment-information">
        <div id="go-logo">
            <img src="<?=$escaper->escapeUrl($block->getLogo());?>" alt="Go Cuotas">
        </div>
        <h2><strong><?=$escaper->escapeHtml(__("Transaction rejected."));?></strong></h2>
        <?php if ($error = $block->getErrorMessage()):?>
            <p><strong><?=$block->escapeHtml($error) ?></strong></p>
        <?php else: ?>
            <p><?=$escaper->escapeHtml(__(
                "There was an error processing your payment. Don't worry, no charge was made to your card."
            ));?></p>
        <?php endif ?>
        <a class="btn-gocuotas"
           href="<?=$escaper->escapeUrl($block->getUrl('gocuotas/order/retry', ['order_id' => $order->getId()]));?>">
            <span><?=$escaper->escapeHtml(__('Retry payment'));?></span>
        </a>
    </div>
<?php else: ?>
    <?php if ($block->getRealOrderId()):?>
        <?php $order = $block->getOrderData();?>
        <p><?=$block->escapeHtml(__('Order #') . $block->getRealOrderId());?></p>
    <?php endif ?>

    <?php if ($error = $block->getErrorMessage()):?>
        <p><strong><?=$block->escapeHtml($error);?></strong></p>
    <?php endif ?>

    <p>
        <?=$block->escapeHtml(
            __(
                'Click <a href="%1">here</a> to continue shopping.',
                $block->escapeUrl($block->getContinueShoppingUrl())
            ),
            ['a']
        ) ?>
    </p>
<?php endif ?>