<?php
/**
 * @author MageRocket
 * @copyright Copyright (c) 2024 MageRocket (https://magerocket.com/)
 * @link https://magerocket.com/
 */

/** @var $block \MageRocket\GoCuotas\Block\Onepage\Success */
/** @var $escaper \Magento\Framework\Escaper */
$order = $block->getOrder();
$payment = $order->getPayment();
$paymentAdditionalInformation = $payment->getAdditionalInformation() ?: [];
?>
<?php if ($block->isPaymentMethodGoCuotas()): ?>
    <div class="gocuotas-payment-information">
        <div id="go-logo">
            <img src="<?=$escaper->escapeUrl($block->getLogo()) ?>" alt="Go Cuotas">
            <h3><?=$escaper->escapeHtml(__('Your payment was processed successfully'));?></h3>
        </div>
        <div class="payment-information">
            <p></p>
            <?php if (isset($paymentAdditionalInformation['id'])): ?>
                <p><?=$escaper->escapeHtml(
                    __('Transaction ID: <b>%1</b>', $paymentAdditionalInformation['id']),
                    ['b']
                );?>
                </p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['status'])): ?>
                <p><?=$escaper->escapeHtml(
                    __('Payment Status: <b>%1</b>', ucfirst($paymentAdditionalInformation['status'])),
                    ['b']
                   );?>
                </p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['installments'])): ?>
                <p><?=$escaper->escapeHtml(
                        __('Installments: <b>%1</b>', $paymentAdditionalInformation['installments']),
                        ['b']
                    );?>
                </p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['card_number'])): ?>
                <p><?=$escaper->escapeHtml(
                        __('Card Number: <b>%1</b>', $paymentAdditionalInformation['card_number']),
                        ['b']
                    );?>
                </p>
            <?php endif;?>
            <?php if (isset($paymentAdditionalInformation['card_name'])): ?>
                <p><?=$escaper->escapeHtml(
                        __('Card Name: <b>%1</b>', $paymentAdditionalInformation['card_name']),
                        ['b']
                    );?>
                </p>
            <?php endif;?>
        </div>
    </div>
<?php endif ?>
